### ISSUE TITLE
Practice submitting a GitHub Pull Request

### ISSUE THREAD

**Issue by jdblischak** [chirunconf/chirunconf19#16]
If you're new to submitting Pull Requests on GitHub (or would like a quick refresher), I have a repository that is dedicated to new contributors practicing how to submit a Pull Request in a learning environment. The repository is [git-for-science](https://github.com/jdblischak/git-for-science) and is associated with a [Git/GitHub tutorial](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004668) that I co-wrote. The full instructions are detailed in the tutorial section [Contribute to Other Projects](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004668#sec011), and a brief list of the steps is also available in the repository's [README file](https://github.com/jdblischak/git-for-science#synopsis-and-motivation).

**Comment by alexpghayes** [comment]
[Another great intro to making a PR for an R package](https://thisisnic.github.io/2018/11/28/ten-steps-to-becoming-a-tidyverse-contributor/) by Nic Crane, in particular about some code she contributed to `broom` a while back.

**Comment by maurolepore** [comment]
Awesome! 
In line with this, I offer support for anyone that feels stuck with the RStudio-Git-GitHub-PR chain. If the mentors are busy helping others, come see me or mention me on GitHub (@maurolepore) or on chirunconf's slack.

I suggest you don't let this slow down your progress during the unconf. Not being familiar with this workflow says nothing about your ability in R (I never used this workflow when I was doing research)

**Comment by jdblischak** [comment]
@anniew completed the tutorial! https://github.com/jdblischak/git-for-science/pull/79
